name: Break Reminders

on:
  schedule:
    # Water (hourly except lunch) - IST = UTC-5:30
    - cron: "0 5-12/1 * * 1-6"   # 10:30–17:30 IST
    - cron: "0 13 * * 1-6"       # 18:30 IST

    # Eye break (every 30 min)
    - cron: "0,30 5-12 * * 1-6"  # 10:30–17:30 IST

    # Walking break (every 3 hours, skipping 1 PM lunch)
    - cron: "30 7,10,13 * * 1-6" # 1 PM skip, so only 1:30, 4:30, 7:30 IST

    # Lunch notification
    - cron: "30 7 * * 1-6"       # 1:00 PM IST

  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests
      - name: Run reminder
        run: python wellness_reminder.py ${{ github.event.schedule || 'water' }}
        env:
          MY_WEBHOOK: ${{ secrets.MY_WEBHOOK }}
          FRIEND_WEBHOOK: ${{ secrets.FRIEND_WEBHOOK }}
